const translations = {
  en: {
    header_home: "Home",
    header_shop: "Shop",
    header_videos: "Videos",
    header_articles: "Articles",
    hero_title: "WINE ENTHUSIASTS, REJOICE!",
    hero_subtitle: "Uncork the joys of wine and the vine with Vinus Social Club",
    shop_button: "SHOP NOW",
    card1_title: "SHOP WINE",
    card1_text: "Explore our curated selection of fine wines.",
    card2_title: "WATCH VIDEOS",
    card2_text: "Sip, swirl, and smile with our fun, informative wine videos.",
    card3_title: "READ ARTICLES",
    card3_text: "Get the latest grape on all things wine with our articles.",
    video_wine_education: "Wine Education",
    education_description: "📚 Discover wine tips, curiosities and knowledge in our educational videos.",
    video_wine_tasting: "Wine Tasting",
    tasting_description: "🍷 Learn and enjoy the art of wine tasting with our exclusive videos.",
    video_wine_tourism: "Wine Tourism",
    tourism_description: "🌍 Follow our travels and explorations through the best wine regions.",
    video_vinus_partys: "Vinus Partys",
    partys_description: "🎉 Relive the best moments of the Vinus parties with the featured videos:",
    watch_button: "WATCH",
    shop_title: "Shop",
    shop_description: "Discover our exclusive wines, curated packs, and unique experiences.",
    article_title: "Articles Section",
    article_description: "Read about wine trends, tips and more.",
    back_home: "HOMEPAGE",
    videos_title: "Videos Section",
    videos_description: "Choose a theme to explore our video content.",
    go_back: "GO BACK",
    footer_about_us: "About Us",
    footer_our_story: "Our Story",
    footer_customer_service: "Customer Service",
    footer_contact: "Contact Us",
    footer_shipping: "Shipping & Returns", 
    footer_faq: "FAQ",
    footer_follow: "Follow Us",
    footer_rights: "©2025 Vinus Social Club, All rights reserved.",
  },
  pt: {
    header_home: "Início",
    header_shop: "Loja",
    header_videos: "Vídeos",
    header_articles: "Artigos",
    hero_title: "ENTUSIASTAS DO VINHO, ALEGREM-SE!",
    hero_subtitle: "Desfrute das alegrias do vinho com o Vinus Social Club",
    shop_button: "COMPRAR",
    card1_title: "COMPRAR VINHO",
    card1_text: "Explore a nossa seleção exclusiva de vinhos.",
    card2_title: "VER VÍDEOS",
    card2_text: "Saboreie e divirta-se com os nossos vídeos informativos sobre vinho.",
    card3_title: "LER ARTIGOS",
    card3_text: "Fique a par de tudo sobre vinhos com os nossos artigos.",
    video_wine_education: "Educação sobre Vinho",
    education_description: "📚 Descobre dicas, curiosidades e conhecimentos sobre vinho nos nossos vídeos educativos.",
    video_wine_tasting: "Prova de Vinhos",
    tasting_description: "🍷 Aprende e desfruta da arte da prova de vinhos com os nossos vídeos exclusivos.",
    video_wine_tourism: "Enoturismo",
    tourism_description: "🌍 Acompanha as nossas viagens e explorações pelas melhores regiões vinícolas.",
    video_vinus_partys: "Festas Vinus",
    partys_description: "🎉 Revive os melhores momentos das festas Vinus com os vídeos em destaque:",
    watch_button: "VER",
    shop_title: "Loja",
    shop_description: "Descubra os nossos vinhos exclusivos, packs especiais e experiências únicas.",
    article_title: "Secção de Artigos",
    article_description: "Lê sobre tendências do vinho, dicas e muito mais.",
    back_home: "PÁGINA INICIAL",
    videos_title: "Secção de Vídeos",
    videos_description: "Escolhe um tema para explorar o nosso conteúdo em vídeo.",
    go_back: "VOLTAR",
    footer_about_us: "Sobre Nós",
    footer_our_story: "A Nossa História",
    footer_customer_service: "Apoio ao Cliente",
    footer_contact: "Contacte-nos",
    footer_shipping: "Envios e Devoluções",
    footer_faq: "Perguntas Frequentes",
    footer_follow: "Siga-nos",
    footer_rights: "©2025 Vinus Social Club, Todos os direitos reservados.",
  },
  fr: {
    header_home: "Accueil",
    header_shop: "Boutique",
    header_videos: "Vidéos",
    header_articles: "Articles",
    hero_title: "AMATEURS DE VIN, RÉJOUISEZ-VOUS !",
    hero_subtitle: "Savourez les plaisirs du vin avec le Vinus Social Club",
    shop_button: "ACHETER",
    card1_title: "ACHETER DU VIN",
    card1_text: "Découvrez notre sélection de vins raffinés.",
    card2_title: "REGARDER LES VIDÉOS",
    card2_text: "Appréciez nos vidéos informatives et amusantes sur le vin.",
    card3_title: "LIRE DES ARTICLES",
    card3_text: "Restez informé sur le vin avec nos articles.",
    video_wine_education: "Éducation sur le vin",
    education_description: "📚 Découvrez des conseils, des curiosités et des connaissances sur le vin dans nos vidéos éducatives.",
    video_wine_tasting: "Dégustation de vin",
    tasting_description: "🍷 Apprenez et profitez de l'art de la dégustation de vin avec nos vidéos exclusives.",
    video_wine_tourism: "Tourisme viticole",
    tourism_description: "🌍 Suivez nos voyages et explorations à travers les meilleures régions viticoles.",
    video_vinus_partys: "Fêtes Vinus",
    partys_description: "🎉 Revivez les meilleurs moments des fêtes Vinus avec nos vidéos sélectionnées :",
    watch_button: "REGARDER",
    shop_title: "Boutique",
    shop_description: "Découvrez nos vins exclusifs, nos packs soignés et des expériences uniques.",
    article_title: "Section des Articles",
    article_description: "Lisez sur les tendances du vin, des conseils et plus encore.",
    back_home: "PAGE D’ACCUEIL",
    videos_title: "Section Vidéos",
    videos_description: "Choisissez un thème pour explorer notre contenu vidéo.",
    go_back: "RETOUR",
    footer_about_us: "À Propos",
    footer_our_story: "Notre Histoire",
    footer_customer_service: "Service Client",
    footer_contact: "Contactez-nous",
    footer_shipping: "Livraison & Retours",
    footer_faq: "FAQ",
    footer_follow: "Suivez-nous",
    footer_rights: "©2025 Vinus Social Club, Tous droits réservés.",
  },
  de: {
    header_home: "Startseite",
    header_shop: "Shop",
    header_videos: "Videos",
    header_articles: "Artikel",
    hero_title: "WEINLIEBHABER, FREUT EUCH!",
    hero_subtitle: "Entkorke die Freuden des Weins mit dem Vinus Social Club",
    shop_button: "JETZT KAUFEN",
    card1_title: "WEIN KAUFEN",
    card1_text: "Entdecke unsere kuratierte Auswahl an Weinen.",
    card2_title: "VIDEOS ANSEHEN",
    card2_text: "Genieße informative und unterhaltsame Videos über Wein.",
    card3_title: "ARTIKEL LESEN",
    card3_text: "Bleib auf dem Laufenden mit unseren spannenden Artikeln über Wein.",
    video_wine_education: "Weinbildung",
    education_description: "📚 Entdecke Weintipps, Kuriositäten und Wissen in unseren Lehrvideos.",
    video_wine_tasting: "Weinverkostung",
    tasting_description: "🍷 Lerne und genieße die Kunst der Weinverkostung mit unseren exklusiven Videos.",
    video_wine_tourism: "Weintourismus",
    tourism_description: "🌍 Begleite unsere Reisen und Erkundungen durch die besten Weinregionen.",
    video_vinus_partys: "Vinus-Partys",
    partys_description: "🎉 Erlebe die besten Momente der Vinus-Partys mit unseren Highlight-Videos noch einmal:",
    watch_button: "ANSCHAUEN",
    shop_title: "Geschäft",
    shop_description: "Entdecken Sie unsere exklusiven Weine, kuratierte Pakete und besondere Erlebnisse.",
    article_title: "Artikelbereich",
    article_description: "Lies über Weintipps, Trends und vieles mehr.",
    back_home: "STARTSEITE",
    videos_title: "Videobereich",
    videos_description: "Wähle ein Thema, um unsere Videoinhalte zu entdecken.",
    go_back: "ZURÜCK",
    footer_about_us: "Über Uns",
    footer_our_story: "Unsere Geschichte",
    footer_customer_service: "Kundendienst",
    footer_contact: "Kontaktieren Sie uns",
    footer_shipping: "Versand & Rückgabe",
    footer_faq: "FAQ",
    footer_follow: "Folgen Sie uns",
    footer_rights: "©2025 Vinus Social Club, Alle Rechte vorbehalten.",
  }
};

document.getElementById("langSelect").addEventListener("change", function () {
  const lang = this.value;
  localStorage.setItem("preferredLanguage", lang);

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
});

document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("preferredLanguage") || "en";
  document.getElementById("langSelect").value = savedLang;

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[savedLang] && translations[savedLang][key]) {
      el.textContent = translations[savedLang][key];
    }
  });
});
